In [22]:
import numpy as np
np.random.seed(1)

In [7]:
X = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]])
X.shape

(4, 2)

In [11]:
Y = np.array([[0,1,1,1]]).T
Y.shape

(4, 1)

In [59]:
syn0 = 2*np.random.random((2,1)) - 1
syn0

array([[-0.72144731],
       [ 0.61478258]])

In [60]:
def sigmoid(x, der=False):
    if der == True:
        return x * (1 - x)
    return 1 / (1 + np.exp(-x))

In [92]:
for i in xrange(1000000):
    
    l0 = X
    l1 = sigmoid(np.dot(l0, syn0))
    
    error = Y - l1
    delta = error * sigmoid(error,True)
    syn0 += np.dot(l0.T, delta)
    
    if i % 100000 == 0:
        print "error :" + str(np.mean(np.abs(error))) + "   Steps :" + str(i)

error :0.125195318389   Steps :0
error :0.125192407179   Steps :100000
error :0.125189622341   Steps :200000
error :0.125186954989   Steps :300000
error :0.125184397091   Steps :400000
error :0.125181941359   Steps :500000
error :0.125179581171   Steps :600000
error :0.125177310487   Steps :700000
error :0.125175123791   Steps :800000
error :0.125173016029   Steps :900000


In [93]:
syn0

array([[ 7.98062981],
       [ 7.98063192]])

In [94]:
l1 = sigmoid(np.dot(X, syn0))
l1

array([[ 0.5       ],
       [ 0.99965809],
       [ 0.99965809],
       [ 0.99999988]])

In [95]:
exp = np.array([[0,1]])
expl = sigmoid(np.dot(exp, syn0))
expl

array([[ 0.99965809]])